---
abstract: 'Paginate DBIx::Class::ResultSets for ExtJS consumption'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires:
  Catalyst::Model::DBIC::Schema: 0.29
  Catalyst::Test: 0
  Catalyst::View::JSON: 0.26
  FindBin: 0
  SQL::Translator: 0.1103
  Test::Deep: 0
  Test::More: 0.92
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-TraitFor-Controller-DoesExtPaging
requires:
  Catalyst::Runtime: 5.8
  Catalyst::TraitFor::Controller::DBIC::DoesPaging: 0.093200
  Web::Util::ExtPaging: 0.001000
resources:
  bugtracker: https://github.com/frioux/Catalyst-TraitFor-Controller-DoesExtPaging/issues
  repository: git://github.com/frioux/Catalyst-TraitFor-Controller-DoesExtPaging.git
version: 1.000000
